<!-- META -->
<meta charset="UTF-8">
<meta name="description" content="Employee Management System">
<meta name="keywords" content="EMS,Employee,Management,System">
<meta name="author" content="Ben Lorantfy, Grigoriy Kozyrev, Michael Dasilva, Kevin Li">
<meta name="isLogged" content="<?=$this->isLogged?>"/>	
<meta name="userType" content="<?=$this->userType?>"/>	
	
<!-- JS -->
<script src = "js/lib/jquery.js"></script>
<script src = "js/lib/underscore.js"></script>
<script src = "js/lib/backbone.js"></script>
<script src = "js/main.js"></script>

<!-- CSS -->
<link rel="stylesheet" href="css/custom.css" title="Custom CSS" type="text/css" media="screen" charset="utf-8">