<!-- META -->
<meta charset="UTF-8">
<meta name="description" content="Employee Management System">
<meta name="keywords" content="EMS,Employee,Management,System">
<meta name="author" content="Ben Lorantfy, Grigoriy Kozyrev, Michael Dasilva, Kevin Li">
<meta name="isLogged" content="<?=$this->isLogged?>"/>	
<meta name="userType" content="<?=$this->userType?>"/>	
	
<!-- JS -->
<script src = "js/lib/jquery.js"></script>
<script src = "js/lib/jqease.js"></script>
<script src = "js/lib/underscore.js"></script>
<script src = "js/lib/backbone.js"></script>
<script src = "js/app.js"></script>					<!-- Creates app -->
<script src = "js/Views/SectionView.js"></script>		
<script src = "js/Views/LoginView.js"></script>		
<script src = "js/Views/SearchView.js"></script>		
<script src = "js/Views/CoverView.js"></script>		
<script src = "js/main.js"></script>				<!-- Runs app -->

<!-- CSS -->
<link rel="stylesheet" href="css/custom.css" title="Custom CSS" type="text/css" media="screen" charset="utf-8">