<section id = "search" style="<?=($this->show)?"":"display:none;"?><?=($this->blurred)?"transform: scale(0.95, 0.95);":""?>">
	<div class = "verticalCenter"></div>
	<div class = "box">
		<div class = "optionsContainer">
			<div class = "optionsSubcontainer">
				<div class = "optionsHeader">Search Options</div>
				<div class = "optionContainer">
					<span class = "verticalAlign"></span>
					<span class = "optionLabel">Sort By:</span>
					<div class = "optionSubcontainer">
						<select class = "option">
							<option>First</option>
							<option>Last</option>
							<option>Date of Birth</option>
						</select>
					</div>
				</div>
				<div class = "optionContainer">
					<span class = "verticalAlign"></span>
					<span class = "optionLabel">Type:</span>
					<div class = "optionSubcontainer">
						<select class = "option">
							<option>Fulltime</option>
							<option>Parttime</option>
							<option>Seasonal</option>
							<option>Contract</option>
						</select>
					</div>
				</div>
				<div class = "optionContainer">
					<span class = "verticalAlign"></span>
					<span class = "optionLabel">Status:</span>
					<div class = "optionSubcontainer">
						<select class = "option">
							<option>All</option>
							<option>Active</option>
							<option>Inactive</option>
							<option>Incomplete</option>
						</select>
					</div>
				</div>
				<div class = "optionsHeader">Actions</div>
				<input class="addEmployeeButton sideBarButton confirmButton" type = "button" value="Add Employee"></input>
				<input class="auditButton sideBarButton button adminControl" type = "button" value="Audit"></input>
				<input class="usersButton sideBarButton button adminControl" type = "button" value="Users"></input>
				<input class="reportsButton sideBarButton button" type = "button" value="Reports"></input>
			</div>
		</div>
		<div class = "resultsContainer">
			<div class = "searchInputContainer">
				<input class = "searchInput" placeholder = "Search" type = "text"></input>
				<img class = "searchIcon" src="assets/images/searchIcon.png"/>
			</div>
			<div class = "results">
				<table class = "resultTable" cellspacing="0" cellpadding="0">
					<tr><td>John</td><td>Doe</td><td>1982 11 23</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>Jane</td><td>Smith</td><td>1990 11 10</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>John</td><td>Doe</td><td>1982 11 23</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>Jane</td><td>Smith</td><td>1990 11 10</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>John</td><td>Doe</td><td>1982 11 23</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>Jane</td><td>Smith</td><td>1990 11 10</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>John</td><td>Doe</td><td>1982 11 23</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>Jane</td><td>Smith</td><td>1990 11 10</td><td>
					<img class = "rowIcon" src = "assets/assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>John</td><td>Doe</td><td>1982 11 23</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
					<tr><td>Jane</td><td>Smith</td><td>1990 11 10</td><td>
					<img class = "rowIcon" src = "assets/images/trash.png"/>
					<img class = "rowIcon" src = "assets/images/clock.png"/>
					<img class = "rowIcon" src = "assets/images/pen.png"/>
					</td></tr>
				</table>
			</div>
		</div>
	</div>
</section>