<section id = "audit" style="<?=($this->show)?"":"display:none;"?>">
	<div class = "sectionBackground"></div>
	<div class = "verticalCenter"></div>
	<div class = "box dialogBox">
		<div class = "sectionTitle">Audit</div>
		<table class = "auditTable" cellspacing="0" cellpadding="2">
			<tr class = "titleRow">
				<td>User ID</td>
				<td>Change time</td>
				<td>Table</td>
				<td>Record ID</td>
				<td>Changed field</td>
				<td>Old Value</td>
				<td>New Value</td>
				<td>Extra</td>
			</tr>
			<?php foreach ($this->auditInfo as $auditEntry): ?>
				<tr class = "titleRow">
					<td><?=$this->auditEntry["user_id"]?></td>
					<td><?=$this->auditEntry["changeTime"]?></td>
					<td><?=$this->auditEntry["changedTable"]?></td>
					<td><?=$this->auditEntry["recordId"]?></td>
					<td><?=$this->auditEntry["changedField"]?></td>
					<td><?=$this->auditEntry["oldValue"]?></td>
					<td><?=$this->auditEntry["newValue"]?></td>
					<td><?=$this->auditEntry["extra"]?></td>
				</tr>						
			<?php endforeach ?>
		</table>
		<div class = "buttonContainer">
			<input type="button" class = "confirmButton bottomButton doneButton" value = "Done"/>
		</div>
	</div>
</section>