<section id = "audit" style="<?=($this->show)?"":"display:none;"?>">
	<div class = "sectionBackground"></div>
	<div class = "verticalCenter"></div>
	<div class = "box dialogBox">
		<div class = "sectionTitle">Audit</div>
		<table class = "auditTable" cellspacing="0" cellpadding="2">
			<tr class = "titleRow">
				<td id="userIdCol">User ID</td>
				<td id="changeTimeCol">Change time</td>
				<td id="tableCol">Table</td>
				<td id="recordIdCol">Record ID</td>
				<td id="changedFieldCol">Changed field</td>
				<td id="oldValCol">Old Value</td>
				<td id="newValCol">New Value</td>
				<td id="typeCol">Type</td>
			</tr>
			<?php foreach ($this->auditInfo as $auditEntry): ?>
				<tr>
					<td><?=$auditEntry["user_id"]?></td>
					<td><?=$auditEntry["changeTime"]?></td>
					<td><?=$auditEntry["changedTable"]?></td>
					<td><?=$auditEntry["recordId"]?></td>
					<td><?=$auditEntry["changedField"]?></td>
					<td><?=$auditEntry["oldValue"]?></td>
					<td><?=$auditEntry["newValue"]?></td>
					<td><?=$auditEntry["extra"]?></td>
				</tr>						
			<?php endforeach ?>
		</table>
	</div>
	<div class = "buttonContainer">
		<input type="button" class = "confirmButton bottomButton doneButton" value = "Done"/>
	</div>
</section>