<section id = "audit" style="<?=($this->show)?"":"display:none;"?>">
	<div class = "sectionBackground"></div>
	<div class = "verticalCenter"></div>
	<div class = "box dialogBox">
		<div class = "sectionTitle">Audit</div>
		<table class = "auditTable" cellspacing="0" cellpadding="2">
			<tr class = "titleRow">
				<td>User ID</td>
				<td>Change time</td>
				<td>Table</td>
				<td>Record ID</td>
				<td>Changed field</td>
				<td>Old Value</td>
				<td>New Value</td>
				<td>Extra</td>
			</tr>
			<?php
				$database = new Database();
				$table = $database->GetAudit();
				echo $table;
			?>
		</table>
		<div class = "buttonContainer">
			<input type="button" class = "confirmButton bottomButton doneButton" value = "Done"/>
		</div>
	</div>
</section>