<?php
	//
	// Templating functions
	// These functions have no logic to them, they're just
	// just used to repeat common markup 
	//
	$this->createField = function($label,$field){
	
		if($this->add){
		
			return "<td>$label:</td><td><input class = '$field' type='text'/></td><td class = 'fieldError'></td>";
		
		}else if($this->view){
		
			return "<td>" . $label . "</td><td><div>" . /* $this->employee->$field */"hi" . "</div><input type = 'text' style = 'display:none' value = '" . /* $this->employee->$field */"hi" . "'></input></td><td class = 'fieldError'></td>";
		
		}
		
	};
	
	//
	// Set UI element text based on mode
	//
	if($this->add){
		// If user is adding employee, set appropiate UI text
		$this->buttonText = "Add";
		$this->title = "Add Employee";
		$this->buttonClass = "addButton";
	}else{
		$this->buttonText = "Edit";
		$this->title = $this->employee->firstName . " " . $this->employee->lastName;
		$this->buttonClass = "editButton";
	}		
?>
<section id = "<?=($this->add)?"addEmployee":"employee"?>" style="<?=($this->show)?"":"display:none;"?>">
	<div class = "sectionBackground"></div>
	<div class = "verticalCenter"></div>
	<div class = "box dialogBox">
		<div class = "sectionTitle"><?=$this->title?></div>
		<table cellspacing="0" cellpadding="0">
			<tr>
				<td>Type:</td>
				<td <?=($this->view) ? 'style="display:none;"' : ""?>>
					<div class = "selectContainer">
						<select class = "employeeType">
							<option value="fullTime">Full Time</option>
							<option value="partTime">Part Time</option>
							<option value="seasonal">Seasonal</option>
							<option class = "adminControl" value="contract">Contract</option>
						</select>
					</div>
				</td>
				<td <?=($this->view) ? "" : 'style="display:none;"'?>>whoa</td>
			</tr>
			<tr class = "field fullTimeField partTimeField seasonalField"><?=$this->createField("First Name","firstName");?></tr>
			<tr class = "field fullTimeField partTimeField seasonalField"><?=$this->createField("Last Name","lastName");?></tr>
			<tr class = "field fullTimeField partTimeField seasonalField"><?=$this->createField("Company Name","companyName");?></tr>
			<tr class = "field fullTimeField partTimeField seasonalField"><?=$this->createField("Date of Birth","dateOfBirth");?></tr>
			<tr class = "field fullTimeField partTimeField seasonalField"><?=$this->createField("Social Insurance Number","sin");?></tr>
			<tr class = "field adminControl fullTimeField partTimeField"><?=$this->createField("Date Hired","dateOfHire");?></tr>
			<tr class = "field adminControl fullTimeField partTimeField"><?=$this->createField("Date Terminated","dateOfTermination");?></tr>
			<tr class = "field adminControl fullTimeField"><?=$this->createField("Salary","salary");?></tr>
			<tr class = "field adminControl partTimeField unselectedField"><?=$this->createField("Hourly Wage","hourlyRate");?></tr>
			<tr class = "field seasonalField unselectedField"><?=$this->createField("Season","season");?></tr>
			<tr class = "field seasonalField unselectedField"><?=$this->createField("Season Year","seasonYear");?></tr>
			<tr class = "field adminControl seasonalField unselectedField"><?=$this->createField("Piece Pay","piecePay");?></tr>
			<tr class = "field adminControl contractField unselectedField"><?=$this->createField("Company Name","contractCompanyName");?></tr>
			<tr class = "field adminControl contractField unselectedField"><?=$this->createField("Date Of Incorporation","dateOfIncorporation");?></tr>
			<tr class = "field adminControl contractField unselectedField"><?=$this->createField("Business Number","businessNumber");?></tr>
			<tr class = "field adminControl contractField unselectedField"><?=$this->createField("Contract Start Date","startDate");?></tr>
			<tr class = "field adminControl contractField unselectedField"><?=$this->createField("Contract Stop Date","endDate");?></tr>
			<tr class = "field adminControl contractField unselectedField"><?=$this->createField("Contract Amount","fixedAmount");?></tr>
			<tr class = "field fullTimeField partTimeField contractField seasonalField" id="reasonOfLeavingTr" style="display:none;"><?=$this->createField("Reason for Leaving","reasonOfLeaving");?></tr>
		</table>
		<div class = "buttonContainer">
			<input type="button" class = "confirmButton bottomButton doneButton" value = "Done"/>
			<input type="button" class = "confirmButton bottomButton <?=$this->buttonClass?>" value = "<?=$this->buttonText?>"/>
		</div>
	</div>
</section>