<section id = "reports" style="display:none;">
	<div class = "sectionBackground"></div>
	<div class = "verticalCenter"></div>
	<div class = "box dialogBox">
		<div class = "sectionTitle">Reports</div>
		<table cellspacing="0" cellpadding="0">
			<tr><td>Seniority Report
				<input id="SeniorityReportCBox" class="rowIcon" name="ReportRadio" type="radio">
			</td></tr>
			<tr><td>Weekly Hours Worked
                <input id="WeeklyHoursWorkedCBox" class="rowIcon" name="ReportRadio" type="radio">
            </td></tr>
			<tr><td>Payroll Report
                <input id="PayRollCBox" class="rowIcon" name="ReportRadio" type="radio">
            </td></tr>
			<tr><td>Active Employment Report
                <input id="ActiveEmploymentReportCBox" class="rowIcon" name="ReportRadio" type="radio">
            </td></tr>
			<tr><td>Inactive Employment Report
                <input id="InactiveEmploymentReportCBox" class="rowIcon" name="ReportRadio" type="radio">
            </td></tr>
		</table>
		<div class = "buttonContainer">
			<input type="button" class = "confirmButton bottomButton doneButton" value = "Done"/>
			<input type="button" class = "confirmButton bottomButton generateButton" value = "Generate"/>
		</div>
	</div>
</section>