<section id = "reports" style="display:none;">
	<div class = "sectionBackground"></div>
	<div class = "verticalCenter"></div>
	<div class = "box dialogBox">
		<div class = "sectionTitle">Reports</div>
		<table cellspacing="0" cellpadding="0">
			<tr>
				<td>Seniority Report</td>
				<td><input class="reportOption" name="ReportRadio" value = "SeniorityReport" type="radio"></td>
			</tr>
			<tr>
				<td>Weekly Hours Worked</td>
             	<td><input class="reportOption" name="ReportRadio" value = "WeeklyHoursWorkedReport" type="radio"></td>
            </tr>
			<tr class = "adminControl">
				<td>Payroll Report</td>
                <td><input class="reportOption" name="ReportRadio" value = "PayRollReport" type="radio"></td>
            </tr>
			<tr class = "adminControl">
				<td>Active Employment Report</td>
                <td><input class="reportOption" name="ReportRadio" value = "ActiveEmploymentReport" type="radio"></td>
            </tr>
			<tr class = "adminControl">
				<td>Inactive Employment Report</td>
                <td><input class="reportOption" name="ReportRadio" value = "InactiveEmploymentReport" type="radio"></td>
            </tr>
		</table>
		<div class = "buttonContainer">
			<input type="button" class = "confirmButton bottomButton doneButton" value = "Done"/>
			<input type="button" class = "confirmButton bottomButton generateButton" value = "Generate"/>
		</div>
	</div>
</section>