<section id = "timecard" style="<?=$this->show ? "" : "display:none;"?>">
	<div class = "sectionBackground"></div>
	<div class = "verticalCenter"></div>
	<div class = "box dialogBox">
		<div class = "sectionTitle">Time Card</div>
		<table cellspacing="0" cellpadding="0">
			<tr>
				<td>Sunday</td>
			</tr>
			<tr>
				<td>Monday</td>
			</tr>
			<tr>
				<td>Tuesday</td>
            </tr>
			<tr>
				<td>Wednesday</td>
            </tr>
			<tr>
				<td>Thursday</td>
            </tr>
			<tr>
				<td>Friday</td>
            </tr>
			<tr>
				<td>Saturday</td>
            </tr>
		</table>
		<div class = "buttonContainer">
			<input type="button" class = "confirmButton bottomButton doneButton" value = "Done"/>
			<input type="button" class = "confirmButton bottomButton generateButton" value = "Generate"/>
		</div>
	</div>
</section>